name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          sudo npm install
      - name: Test
        run: npm run test

  # build-alpine:
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       node-version: [14, 16, 18]
  #   container:
  #     image: node:${{ matrix.node-version }}-alpine
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: |
  #         apk add make g++ python3
  #     - name: Test
  #       run: |
  #         npm test --unsafe-perm
